<?php

/********IF THE POST HAS A SOULTHEME CUSTOM FOOTER TEMPLATE********/

// Check the post to see if it has a custom footer template id
$saved_custom_templates = get_post_meta($post->ID, 'gsr-soul-theme-custom-post-templates', true);

// If it does have a custom footer template id
if(isset($saved_custom_templates['_footer']) && 'null' !== $saved_custom_templates['_footer']){

    // Confirm that the id belongs to an existing template that is generated by BB
    $template = get_posts(array('numberposts' => 1, 'post_type' => 'fl-builder-template', 'p' => intval($saved_custom_templates['_footer']) ));
    if(!empty($template)){

        // If we've found a template, output our custom footer code
        // We're including the default footer actions here in case something relys on them
            do_action( 'fl_content_close' ); ?>

            </div><!-- .fl-page-content -->
            <?php

            do_action( 'fl_after_content' );

            if ( FLTheme::has_footer() ) :

            ?>
            <footer class="fl-page-footer-wrap"<?php FLTheme::print_schema( ' itemscope="itemscope" itemtype="https://schema.org/WPFooter"' ); ?>>
                <?php
                // Query and render the custom template
                FLBuilder::render_query( array(
                    'post_type' => 'fl-builder-template',
                    'p'         => $template[0]->ID
                ) );
                
                ?>
            </footer>
            <?php endif; ?>
            <?php do_action( 'fl_page_close' ); ?>
        </div><!-- .fl-page -->
        <?php

        wp_footer();

        do_action( 'fl_body_close' );

        FLTheme::footer_code();

        ?>
        </body>
        </html>

        <?php
        // And stop the execution here since we've outputted our custom footer
        return;
    }
    
}

/********IF THE POST DOES NOT HAVE A SOULTHEME CUSTOM FOOTER TEMPLATE********/

// If there is no saved footer template, or the footer process fails along the way, default to original theme's footer
?>

<?php do_action( 'fl_content_close' ); ?>

	</div><!-- .fl-page-content -->
	<?php

	do_action( 'fl_after_content' );

	if ( FLTheme::has_footer() ) :

		?>
	<footer class="fl-page-footer-wrap"<?php FLTheme::print_schema( ' itemscope="itemscope" itemtype="https://schema.org/WPFooter"' ); ?>>
		<?php

		do_action( 'fl_footer_wrap_open' );
		do_action( 'fl_before_footer_widgets' );

		FLTheme::footer_widgets();

		do_action( 'fl_after_footer_widgets' );
		do_action( 'fl_before_footer' );

		FLTheme::footer();

		do_action( 'fl_after_footer' );
		do_action( 'fl_footer_wrap_close' );

		?>
	</footer>
	<?php endif; ?>
	<?php do_action( 'fl_page_close' ); ?>
</div><!-- .fl-page -->
<?php

wp_footer();

do_action( 'fl_body_close' );

FLTheme::footer_code();

?>
</body>
</html>






